<?php

namespace App\Filament\Resources\LocationPages;

use App\Filament\Resources\LocationPages\Pages\CreateLocationPage;
use App\Filament\Resources\LocationPages\Pages\EditLocationPage;
use App\Filament\Resources\LocationPages\Pages\ListLocationPages;
use App\Filament\Resources\LocationPages\Pages\ViewLocationPage;
use App\Filament\Resources\LocationPages\Schemas\LocationPageForm;
use App\Filament\Resources\LocationPages\Schemas\LocationPageInfolist;
use App\Filament\Resources\LocationPages\Tables\LocationPagesTable;
use App\Models\LocationPage;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;

class LocationPageResource extends Resource
{
    protected static ?string $model = LocationPage::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedMapPin;

    protected static ?string $navigationLabel = 'Location Pages';

    protected static ?string $recordTitleAttribute = 'title';

    protected static ?int $navigationSort = 5;

    public static function form(Schema $schema): Schema
    {
        return LocationPageForm::configure($schema);
    }

    public static function infolist(Schema $schema): Schema
    {
        return LocationPageInfolist::configure($schema);
    }

    public static function table(Table $table): Table
    {
        return LocationPagesTable::configure($table);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListLocationPages::route('/'),
            'view' => ViewLocationPage::route('/{record}'),
            'edit' => EditLocationPage::route('/{record}/edit'),
        ];
    }

    public static function canCreate(): bool
    {
        return false; // Pages are generated by command, not manually created
    }
}
